import "./globals.css";

import { i18n } from "../../i18n-config";
import { Locale } from "@/i18n-config";

import ThemeToggleProvider from "@/providers/ThemeToggleProvider";

import NavBar from "@/components/navbars/NavBar";


export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}
export const metadata = {
  title: "AIFusion",
  description: "Generated by zizdlp.com",
};
export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { lang: Locale };
}) {
  return (
    <html lang={params.lang} suppressHydrationWarning>
      <head>
        <link rel="icon" href="/logo.svg" sizes="any" />
      </head>
      <body className="antialiased text-slate-500 dark:text-slate-400 bg-white dark:bg-slate-900 min-h-screen">


                    <ThemeToggleProvider>

                        <NavBar lang={params.lang} />
                        {children}
        
                    </ThemeToggleProvider>

      </body>
    </html>
  );
}
